default_platform(:mac)

platform :mac do
  desc "Build and export the app for macOS Intel (x86_64) and Apple Silicon (arm64)"
  lane :build do
    build_mac_app(
      project: "Timer/Pigeon Timer.xcodeproj",
      scheme: "Pigeon Timer",
      configuration: "Release",
      export_method: "app-store",
      verbose: true,
      export_options: {
        provisioningProfiles: {
          "com.benallfree.pigeon" => "com.benallfree.pigeon",
        }
      }
    )
  end

  desc "Publish the latest build to the Apple App Store"
  lane :publish do
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key: ENV["APP_STORE_CONNECT_KEY"],
      in_house: false,
    )

    upload_to_app_store(
      platform: "osx",
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end
